#!/usr/bin/env python3
"""Simple helper to ignore gitfiles
"""

import argparse
import os
import os.path
import sys


def main():
    args = parser.parse_args()
    command = getattr(args, 'command', 'write')

    try:
        command = globals()[f'command_{command}']

    except KeyError:
        print(f'unrecognized command {command}', file=sys.stderr)
        print(file=sys.stderr)

        command_help(args)
        raise SystemExit(1)

    command(args)


def command_help(args):
    parser.print_help()


def command_write(args):
    basedir = os.path.abspath('.')

    if os.path.exists(os.path.join(basedir, '.gitignore')):
        print('.gitignore file already exists', file=sys.stderr)
        raise SystemExit(1)

    with open(os.path.join(basedir, '.gitignore'), 'w') as fobj:
        print('*', file=fobj)


parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers()

help_parser = subparsers.add_parser('help', help='Default')
help_parser.set_defaults(command='help')


if __name__ == "__main__":
    main()
